services:

  mongodb:
    image: mongo
    volumes:
      - mongodb-volume:/data/db
    ports:
      - "27018:27017"
    restart: always

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/gamehub

volumes:
  mongodb-volume: